import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#fbf9f8",
        "surface-main": "#fbf9f8",
        "surface-card": "#ffffff",
        "surface-container": "#efedec",
        "surface-container-low": "#f5f3f2",
        "surface-container-high": "#e9e8e7",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e4e2e1",
        surface: "#fbf9f8",
        "surface-dim": "#dbdad9",
        "surface-bright": "#fbf9f8",
        "surface-variant": "#e4e2e1",
        "surface-tint": "#a93539",
        "on-surface": "#1b1c1b",
        "on-surface-variant": "#574140",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f2f0ef",
        outline: "#8b7170",
        "outline-variant": "#debfbe",
        "border-subtle": "#e5e1e0",
        primary: "#a93539",
        "on-primary": "#ffffff",
        "primary-action": "#f06a6a",
        "primary-container": "#f06a6a",
        "on-primary-container": "#62000e",
        "inverse-primary": "#ffb3b0",
        "primary-fixed": "#ffdad8",
        "primary-fixed-dim": "#ffb3b0",
        "on-primary-fixed": "#410006",
        "on-primary-fixed-variant": "#881d24",
        "primary-soft": "#fff0ef",
        secondary: "#5f6368",
        "on-secondary": "#ffffff",
        "secondary-container": "#dde0e6",
        "on-secondary-container": "#5f6368",
        "secondary-fixed": "#dfe3e8",
        "secondary-fixed-dim": "#c3c7cc",
        "on-secondary-fixed": "#181c20",
        "on-secondary-fixed-variant": "#43474c",
        tertiary: "#006c48",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00aa74",
        "on-tertiary-container": "#003522",
        "tertiary-fixed": "#77fbbd",
        "tertiary-fixed-dim": "#58dea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-soft": "#e8f8f1",
        "broadcast-blue": "#1a73e8",
        "text-heading": "#202124",
        "text-body": "#5f6368",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "Inter", "system-ui", "sans-serif"],
        data: ["Inter", "Hanken Grotesk", "system-ui", "sans-serif"],
        "display-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-sm": ["Hanken Grotesk"],
        "data-tabular": ["Inter"],
        "title-sm": ["Hanken Grotesk"],
        "label-caps": ["Inter"],
        "body-md": ["Hanken Grotesk"]
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "data-tabular": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      boxShadow: {
        soft: "0 12px 30px rgba(65, 0, 6, 0.07)",
      },
      spacing: {
        "row-height-standard": "56px",
        "margin-page": "2rem",
        "container-max-width": "1600px",
        "sidebar-width": "260px",
        "row-height-dense": "40px",
        "gutter": "1.5rem"
      }
    },
  },
  plugins: [],
} satisfies Config;

